import { createApp } from 'vue';
import './assets/styles.css';
import App from './App.vue';
import router from './router/router.js'; 
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
import { far } from '@fortawesome/free-regular-svg-icons';
import { fab } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
// import Vue from 'vue';
import VueCarousel from 'vue-carousel';
library.add(fas, far, fab);
const app = createApp(App);
app.component('font-awesome-icon', FontAwesomeIcon);
app.use(router);
app.use(VueCarousel);
app.mount('#app');
